spring:
  application:
    name: account

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: secret123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 2727

springdoc:
  api-docs:
    path: /api-docs
